//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AML_Projects.TMS_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TMS_Service.ITMS_Service")]
    public interface ITMS_Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITMS_Service/DoWork", ReplyAction="http://tempuri.org/ITMS_Service/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITMS_Service/DoWork", ReplyAction="http://tempuri.org/ITMS_Service/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITMS_Service/TestService", ReplyAction="http://tempuri.org/ITMS_Service/TestServiceResponse")]
        string TestService(string flag, string empcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITMS_Service/TestService", ReplyAction="http://tempuri.org/ITMS_Service/TestServiceResponse")]
        System.Threading.Tasks.Task<string> TestServiceAsync(string flag, string empcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITMS_Service/TreasuryFillData", ReplyAction="http://tempuri.org/ITMS_Service/TreasuryFillDataResponse")]
        System.Data.DataSet TreasuryFillData(string flag, string PageVal, string PagePara, string PagePar1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITMS_Service/TreasuryFillData", ReplyAction="http://tempuri.org/ITMS_Service/TreasuryFillDataResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> TreasuryFillDataAsync(string flag, string PageVal, string PagePara, string PagePar1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITMS_Service/TresuryConfirmations", ReplyAction="http://tempuri.org/ITMS_Service/TresuryConfirmationsResponse")]
        string TresuryConfirmations(string flag, string PagePara, string PagePara1, string PagePar2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITMS_Service/TresuryConfirmations", ReplyAction="http://tempuri.org/ITMS_Service/TresuryConfirmationsResponse")]
        System.Threading.Tasks.Task<string> TresuryConfirmationsAsync(string flag, string PagePara, string PagePara1, string PagePar2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITMS_Service/TreasuryFillingData", ReplyAction="http://tempuri.org/ITMS_Service/TreasuryFillingDataResponse")]
        System.Data.DataSet TreasuryFillingData(string flag, string PageVal, string ParVal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITMS_Service/TreasuryFillingData", ReplyAction="http://tempuri.org/ITMS_Service/TreasuryFillingDataResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> TreasuryFillingDataAsync(string flag, string PageVal, string ParVal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITMS_Service/TreasuryConfirm", ReplyAction="http://tempuri.org/ITMS_Service/TreasuryConfirmResponse")]
        string TreasuryConfirm(string flag, string Param, string PageValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITMS_Service/TreasuryConfirm", ReplyAction="http://tempuri.org/ITMS_Service/TreasuryConfirmResponse")]
        System.Threading.Tasks.Task<string> TreasuryConfirmAsync(string flag, string Param, string PageValue);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITMS_ServiceChannel : AML_Projects.TMS_Service.ITMS_Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TMS_ServiceClient : System.ServiceModel.ClientBase<AML_Projects.TMS_Service.ITMS_Service>, AML_Projects.TMS_Service.ITMS_Service {
        
        public TMS_ServiceClient() {
        }
        
        public TMS_ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TMS_ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TMS_ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TMS_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public string TestService(string flag, string empcode) {
            return base.Channel.TestService(flag, empcode);
        }
        
        public System.Threading.Tasks.Task<string> TestServiceAsync(string flag, string empcode) {
            return base.Channel.TestServiceAsync(flag, empcode);
        }
        
        public System.Data.DataSet TreasuryFillData(string flag, string PageVal, string PagePara, string PagePar1) {
            return base.Channel.TreasuryFillData(flag, PageVal, PagePara, PagePar1);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TreasuryFillDataAsync(string flag, string PageVal, string PagePara, string PagePar1) {
            return base.Channel.TreasuryFillDataAsync(flag, PageVal, PagePara, PagePar1);
        }
        
        public string TresuryConfirmations(string flag, string PagePara, string PagePara1, string PagePar2) {
            return base.Channel.TresuryConfirmations(flag, PagePara, PagePara1, PagePar2);
        }
        
        public System.Threading.Tasks.Task<string> TresuryConfirmationsAsync(string flag, string PagePara, string PagePara1, string PagePar2) {
            return base.Channel.TresuryConfirmationsAsync(flag, PagePara, PagePara1, PagePar2);
        }
        
        public System.Data.DataSet TreasuryFillingData(string flag, string PageVal, string ParVal) {
            return base.Channel.TreasuryFillingData(flag, PageVal, ParVal);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TreasuryFillingDataAsync(string flag, string PageVal, string ParVal) {
            return base.Channel.TreasuryFillingDataAsync(flag, PageVal, ParVal);
        }
        
        public string TreasuryConfirm(string flag, string Param, string PageValue) {
            return base.Channel.TreasuryConfirm(flag, Param, PageValue);
        }
        
        public System.Threading.Tasks.Task<string> TreasuryConfirmAsync(string flag, string Param, string PageValue) {
            return base.Channel.TreasuryConfirmAsync(flag, Param, PageValue);
        }
    }
}
